#!/usr/bin/env bash
#while using while loop to read the file /etc/passwd line by line
userid=0
while IFS=: read -r username _ _ gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $info"
    ((userid++))
done < /etc/passwd
