#!/bin/env bash

# Using while loop to read the file /etc/passwd line by line
while IFS=: read -r username _ uid gid info home shell; do
    # Printing the content of each line
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Group ID: $gid"
    echo "Info: $info"
    echo "Home directory: $home"
    echo "Shell: $shell"
    echo ""
done < /etc/passwd

