#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file
while IFS=: read -r username _ uid gid _ home shell; do
    password=$(grep -E "^$username:" /etc/shadow | cut -d: -f2)
    info=$(grep -E "^$username:" /etc/passwd | cut -d: -f5)

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
