#!/usr/bin/env bash
#This is a bash script that prints "Best school" 10 times using while loop
i=0

# Using a while loop to display "Best School" 10 times
while [ $i -lt 10 ]; do
    echo "Best School"
    ((i++))
done
