#!/usr/bin/env bash
#Script that manages another script

start() {
./manage_my_process &
echo $! > /var/run/my_process.pid
echo "manage_my_process startes"
}

stop () {
pkill -f "./manage_my_process"
rm /var/run/my_process.pid
echo "manage_my_process stopped"
}

restart () {
pkill -f "./manage_my_process"
rm /var/run/my_process.pid 
./manage_my_process &
echo $! >> /var/run/my_process.pid
echo "manage_my_processs restarted"
}

case "$1" in
start) start ;;
stop) stop ;;
restart) restart ;;
*) echo "Usage: manage_my_process {start|stop|restart}"

;;

esac
