#!/usr/bin/env bash
#Process that manages another process

case "$1" in
    start)
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process is already running."
        else
            nohup /path/to/manage_my_process >/dev/null 2>&1 &
            echo $! >/var/run/my_process.pid
            echo "manage_my_process started."
        fi
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill $pid
            rm /var/run/my_process.pid
            echo "manage_my_process stopped."
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill $pid
            rm /var/run/my_process.pid
        fi
        nohup /path/to/manage_my_process >/dev/null 2>&1 &
        echo $! >/var/run/my_process.pid
        echo "manage_my_process restarted."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
