#!/usr/bin/env bash
#Script that uses kill that stops To infinity and beyond
prog_pid=()
readarray -t prog_pid < < (preg -la -x ".bash*" | grep '4-to_infinity_and_beyond' | cut -d ' ' -f 1)
for ((i=0;i <"${#prog_pid[i]}"; i++)) do
kill -s SIGTERM "${prog_pid[i]}"
done
