#!/usr/bin/env bash
#Display I am alive every two seconds
while :                                            
do                                                 
        echo "I am alive!" >> /tmp/my_process      
        sleep 2                                    
done
